[build]
  publish = "dist/"
  command = "yarn build:prod"

[context.production.environment]
  YARN_VERSION = "1.22.4"
  NODE_VERSION = "12"
  API_HOST = "https://tchak-create-note.builtwithdark.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"

  [headers.values]
    Cache-Control = "public, max-age=365000000, immutable"

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
